name: librespot

on:
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: librespot-org/librespot
    - name: Build
      run: | 
        wget https://downloads.openwrt.org/releases/23.05.2/targets/bcm27xx/bcm2708/openwrt-sdk-23.05.2-bcm27xx-bcm2708_gcc-12.3.0_musl_eabi.Linux-x86_64.tar.xz
        mv openwrt-sdk* /sdk
        export STAGING_DIR=/sdk/staging_dir
        export PATH=/sdk/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/bin:/root/.cargo/bin:$PATH:/usr/bin:/bin:/usr/sbin:/sbin
        mkdir .cargo
        echo '[target.mipsel-unknown-linux-musl]\nlinker = "mipsel-openwrt-linux-gcc"' > .cargo/config
        echo '\n[profile.release]\nlto = "thin"\ndebug = 0\npanic = "abort"\nincremental = false\ncodegen-units = 1\nopt-level = "s"' >> Cargo.toml
        rustup target add mipsel-unknown-linux-musl
        cargo fetch --target mipsel-unknown-linux-musl --locked
        cargo build --release --target mipsel-unknown-linux-musl --locked --no-default-features
