name: Compile librespot

on:
  workflow_dispatch:
  workflow_call:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: config
      
    - name: Load configuration from repo
      run: |
          cat config/config
          cat config/config >> $GITHUB_ENV
          
    - uses: actions/checkout@v4
      with:
        repository: librespot-org/librespot
        path: librespot
        
    - name: Build
      run: | 
        GCC_VERSION=12.3.0
        ARCH=aarch65
        cd librespot
        curl -Os https://downloads.openwrt.org/releases/${{ env.openwrt_version }}/targets/bcm27xx/bcm2708/openwrt-sdk-${{ env.openwrt_version }}-${{ env.image }}_gcc-${GCC_VERSION}_musl.Linux-x86_64.tar.xz
        tar xf openwrt-sdk-*.tar.* && rm openwrt-sdk-*.tar.*
        mv openwrt-sdk* owsdk
        ls -la $GITHUB_WORKSPACE/librespot/owsdk/staging_dir/
        export STAGING_DIR=$GITHUB_WORKSPACE/librespot/owsdk/staging_dir
        export PATH=$GITHUB_WORKSPACE/librespot/owsdk/staging_dir/toolchain-$ARCH_cortex-a53_gcc-$GCC_VERSION_musl/bin:/root/.cargo/bin:$PATH:/usr/bin:/bin:/usr/sbin:/sbin
        mkdir .cargo
        echo '[target.$ARCH-unknown-linux-musl]' > .cargo/config
        echo 'linker = "$ARCH-openwrt-linux-gcc"' >> .cargo/config
        echo '' >> Cargo.toml
        echo '[profile.release]' >> Cargo.toml
        echo 'lto = "thin"' >> Cargo.toml
        echo 'debug = 0' >> Cargo.toml
        echo 'panic = "abort"' >> Cargo.toml
        echo 'incremental = false' >> Cargo.toml
        echo 'codegen-units = 1' >> Cargo.toml
        echo 'opt-level = "s"' >> Cargo.toml
        rustup target add $ARCH-unknown-linux-musl
        cargo fetch --target $ARCH-unknown-linux-musl --locked
        cargo build --release --target $ARCH-unknown-linux-musl --locked --no-default-features
        
    - uses: actions/upload-artifact@v3
      with:
        name: librespot
        path: librespot/target/aarch64-unknown-linux-musl/release/librespot
