name: Create image

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  #compile-librespot:
    #uses: ./.github/workflows/librespot.yml
  
  create-image:
    #needs: compile-librespot
    
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      
      - uses: actions/checkout@v3
      
      - name: Load configuration from repo
        run: |
          cat config
          cat config >> $GITHUB_ENV
      
      #- uses: actions/download-artifact@v3
      #  with:
      #   name: librespot
      #   path: files/usr/bin/
      
      - name: Build openwrt image
        uses: izer-xyz/openwrt-imagebuilder-action@v4
        with:
          profile: ${{ env.profile }}
          openwrt-version: ${{ env.openwrt_version }}
          packages: ${{ env.packages }}
          debug: ${{ env.debug }}
          files: files
          disabled-services: ${{ env.disabled_services }}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.openwrt_version }}-${{ github.run_number }}
          body: |
            Custom OpenWrt build ...
            
            * OpenWrt version: ${{ env.openwrt_version }}
            * Profile: ${{ env.profile }}
            * Packages: ${{ env.packages }}
            
          files: |
            bin/*
