name: Create image

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  create-image:
    
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      
      - uses: actions/checkout@v3
      
      - name: Load configuration from repo
        run: |
          cat config
          cat config >> $GITHUB_ENV
      
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "izer-xyz/librespot-openwrt"
          latest: true
          fileName: "*.ipk"
          out-file-path: "packages"
        
      - name: Build openwrt image
        uses: izer-xyz/openwrt-imagebuilder-action@v6
        with:
          image: ${{ env.image }}
          openwrt-version: ${{ env.openwrt_version }}
          packages: ${{ env.packages }}
          debug: ${{ env.debug }}
          files: files
          disabled-services: ${{ env.disabled_services }}
          rootfs-size: 512
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.openwrt_version }}-${{ env.image }}-${{ github.run_number }}
          body: |
            Custom OpenWrt build ...
            
            * OpenWrt version: ${{ env.openwrt_version }}
            * Image: ${{ env.image }}
            * Packages: ${{ env.packages }}
            
          files: |
            bin/*
